const TOKEN =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJMZWFkU291cmNlSWQiOiIiLCJDdXN0b21lcklEIjoiNTU3NjYiLCJTZXNzaW9uSUQiOiJjMDI3MzZmNC1kODQzLTRmMjAtODM5Mi1hZmU1MWMxOWZlNDUiLCJDUk1UcmFuc2FjdGlvbklkIjoiIiwiQ1JNVXNlcklkIjoiIiwiQ1JNTG9jYXRpb25JZCI6IiIsIkVtYWlsIjoiIiwiUGhvbmVOdW1iZXIiOiIiLCJDdXN0b21lckF1dGhUeXBlIjozLCJJc1NpZ25JbiI6ZmFsc2UsIklzR3Vlc3QiOnRydWUsIklzQ1JNVXNlciI6ZmFsc2UsIklwQWRkcmVzcyI6IjEyNy4wLjAuMSIsIlRlbmFudElkIjoiMzIiLCJuYmYiOjE2OTU3MTk3MTAsImV4cCI6MTY5NTgwNjExMCwiaXNzIjoiQmVybXVkYSBTb2Z0IiwiYXVkIjoiSXpzdXJlIFJhdGluZyJ9.nbc-zq-XP_Vy4DdFpysFzY-BgQfWO0VDdNTfRqmKkeI";

const authConfig = {
  headers: { Authorization: `Bearer ${TOKEN}` },
};

export { authConfig };
